server:
  port: 8080

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: Board
          uri: lb://board
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/(?<segment>.*), /$\{segment}