server:
  port: 8080

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: board
          uri: lb://Board
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/(?<board>.*), /$\{board}


        - id: Member
          uri: lb://member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<member>.*), /$\{member}
